### ISSUE TITLE
Use bind mount to put brew in /home/linuxbrew

### ISSUE THREAD

**Issue by tseemann** [gvlproject/microgvl.ansible.filesystem#50]
Linuxbrew does much better when it is in `/home/linuxbrew/.linuxbrew`. We can use "bind mounts" to do this without using the root partition.

```
# login as ubuntu

sudo mkdir /mnt/linuxbrew 
sudo chown ubuntu:ubuntu /mnt/linuxbrew 
sudo mkdir /home/linuxbrew

# the following is TEMPORARY, need to put in /etc/fstab
mount --bind /mnt/linuxbrew /home/linuxbrew

git clone https://github.com/Linuxbrew/brew.git /home/linuxbrew/.linuxbrew
```

Then in `/etc/profile.d/linuxbrew*`, need to fix the PATHS to use `/home/linuxbrew/.linuxbrew` and also `unset LD_LIBRARY_PATH`.

```
brew install hello

# important to get these in first (might be others too)
brew install gcc python python3 

# then the rest
brew tap homebrew/science
brew tap tseemann/homebrew-bioinformatics-linux
brew install nullarbor snippy prokka
```

**Comment by Slugger70** [comment]
We can't put linuxbrew in /mnt.. It needs to be part of the /mnt/gvl/... path system so it is included in the apps archive.

It will have to still go into /mnt/gvl/apps/linuxbrew...

The mkdir and mount bind commands will need to be run post boot on EVERY new instance of the mGVL.. This is because the GVL image doesn't have /home/linuxbrew... home for users is actually located in /mnt/galaxy/home... 

It will add to the start up time of any new mGVL (not necessarily a problem) but over zealous users who don't wait for the setup scripts to complete will be wondering why nothing works... (This happens now too BTW..)

**Comment by Slugger70** [comment]
Simon to re-write the linuxbrew install script to do it this way.

**Comment by tseemann** [comment]
I think it can still go in `fstab` or udev.rules or something to make it mount when it gets to that point?    

I feel like the GVL needs a professional sysadmin on the team. It's so complicated.
